steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
          'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/myimage', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/myimage']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'helloworld', 
          '--image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/myimage', 
          '--region', 'asia-northeast1', '--platform', 'managed']
