services:
  backend:
    platform: linux/x86_64
    environment:
      - GO_ENV=production
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    stdin_open: true
